"use strict";
let myNames = document.getElementById('name');
let desig = document.getElementById('desig');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let add = document.getElementById('add');
let pass1 = document.getElementById('pass1');
let deg1 = document.getElementById('deg1');
let inst1 = document.getElementById('inst1');
let pass2 = document.getElementById('pass2');
let deg2 = document.getElementById('deg2');
let inst2 = document.getElementById('inst2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let skill4 = document.getElementById('skill4');
let skill5 = document.getElementById('skill5');
let skill6 = document.getElementById('skill6');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let ref = document.getElementById('ref');
let about = document.getElementById('about');
let pic = document.getElementById('pic');
let stYear = document.getElementById('stYear');
let endYear = document.getElementById('endYear');
let company = document.getElementById('company');
let comLocation = document.getElementById('comLocation');
let jobTitle = document.getElementById('jobTitle');
let achv1 = document.getElementById('achv1');
let achv2 = document.getElementById('achv2');
let achv3 = document.getElementById('achv3');
let stYear1 = document.getElementById('stYear1');
let endYear1 = document.getElementById('endYear1');
let company1 = document.getElementById('company1');
let comLocation1 = document.getElementById('comLocation1');
let jobTitle1 = document.getElementById('jobTitle1');
let achv11 = document.getElementById('achv11');
let achv22 = document.getElementById('achv22');
let achv33 = document.getElementById('achv33');
let stYear2 = document.getElementById('stYear2');
let endYear2 = document.getElementById('endYear2');
let company2 = document.getElementById('company2');
let comLocation2 = document.getElementById('comLocation2');
let jobTitle2 = document.getElementById('jobTitle2');
let achv111 = document.getElementById('achv111');
let achv222 = document.getElementById('achv222');
let achv333 = document.getElementById('achv333');
let submitBtn = document.getElementById('submitBtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem("name", myNames.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("inst1", inst1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("inst2", inst2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("skill5", skill5.value);
    localStorage.setItem("skill6", skill6.value);
    localStorage.setItem("lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("ref", ref.value);
    localStorage.setItem("about", about.value);
    localStorage.setItem("stYear", stYear.value);
    localStorage.setItem("endYear", endYear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("comLocation", comLocation.value);
    localStorage.setItem("jobTitle", jobTitle.value);
    localStorage.setItem("achv1", achv1.value);
    localStorage.setItem("achv2", achv2.value);
    localStorage.setItem("achv3", achv3.value);
    localStorage.setItem("stYear1", stYear1.value);
    localStorage.setItem("endYear1", endYear1.value);
    localStorage.setItem("company1", company1.value);
    localStorage.setItem("comLocation1", comLocation1.value);
    localStorage.setItem("jobTitle1", jobTitle1.value);
    localStorage.setItem("achv11", achv11.value);
    localStorage.setItem("achv22", achv22.value);
    localStorage.setItem("achv33", achv33.value);
    localStorage.setItem("stYear2", stYear2.value);
    localStorage.setItem("endYear2", endYear2.value);
    localStorage.setItem("company2", company2.value);
    localStorage.setItem("comLocation2", comLocation2.value);
    localStorage.setItem("jobTitle2", jobTitle2.value);
    localStorage.setItem("achv111", achv111.value);
    localStorage.setItem("achv222", achv222.value);
    localStorage.setItem("achv333", achv333.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/resume.html";
});
