let myNames:any = document.getElementById('name')
let desig:any = document.getElementById('desig')
let phone:any = document.getElementById('phone')
let email:any = document.getElementById('email')
let add:any = document.getElementById('add')
let pass1:any = document.getElementById('pass1')
let deg1:any = document.getElementById('deg1')
let inst1:any = document.getElementById('inst1')
let pass2:any = document.getElementById('pass2')
let deg2:any = document.getElementById('deg2')
let inst2:any = document.getElementById('inst2')
let skill1:any = document.getElementById('skill1')
let skill2:any = document.getElementById('skill2')
let skill3:any = document.getElementById('skill3')
let skill4:any = document.getElementById('skill4')
let skill5:any = document.getElementById('skill5')
let skill6:any = document.getElementById('skill6')
let lang1:any = document.getElementById('lang1')
let lang2:any = document.getElementById('lang2')
let ref:any = document.getElementById('ref')
let about:any = document.getElementById('about')
let pic:any = document.getElementById('pic')
let stYear:any = document.getElementById('stYear')
let endYear:any = document.getElementById('endYear')
let company:any = document.getElementById('company')
let comLocation:any = document.getElementById('comLocation')
let jobTitle:any = document.getElementById('jobTitle')
let achv1:any = document.getElementById('achv1')
let achv2:any = document.getElementById('achv2')
let achv3:any = document.getElementById('achv3')
let stYear1:any = document.getElementById('stYear1')
let endYear1:any = document.getElementById('endYear1')
let company1:any = document.getElementById('company1')
let comLocation1:any = document.getElementById('comLocation1')
let jobTitle1:any = document.getElementById('jobTitle1')
let achv11:any = document.getElementById('achv11')
let achv22:any = document.getElementById('achv22')
let achv33:any = document.getElementById('achv33')
let stYear2:any = document.getElementById('stYear2')
let endYear2:any = document.getElementById('endYear2')
let company2:any = document.getElementById('company2')
let comLocation2:any = document.getElementById('comLocation2')
let jobTitle2:any = document.getElementById('jobTitle2')
let achv111:any = document.getElementById('achv111')
let achv222:any = document.getElementById('achv222')
let achv333:any = document.getElementById('achv333')


let submitBtn = document.getElementById('submitBtn')
let form = document.getElementById('form')

form?.addEventListener('submit', (e)=>{
e.preventDefault()

localStorage.setItem("name", myNames.value)
localStorage.setItem("desig", desig.value)
localStorage.setItem("phone", phone.value)
localStorage.setItem("email", email.value)
localStorage.setItem("add", add.value)
localStorage.setItem("pass1", pass1.value)
localStorage.setItem("deg1", deg1.value)
localStorage.setItem("inst1", inst1.value)
localStorage.setItem("pass2", pass2.value)
localStorage.setItem("deg2", deg2.value)
localStorage.setItem("inst2", inst2.value)
localStorage.setItem("skill1", skill1.value)
localStorage.setItem("skill2", skill2.value)
localStorage.setItem("skill3", skill3.value)
localStorage.setItem("skill4", skill4.value)
localStorage.setItem("skill5", skill5.value)
localStorage.setItem("skill6", skill6.value)
localStorage.setItem("lang1", lang1.value)
localStorage.setItem("lang2", lang2.value)
localStorage.setItem("ref", ref.value)
localStorage.setItem("about", about.value)
localStorage.setItem("stYear", stYear.value)
localStorage.setItem("endYear", endYear.value)
localStorage.setItem("company", company.value)
localStorage.setItem("comLocation", comLocation.value)
localStorage.setItem("jobTitle", jobTitle.value)
localStorage.setItem("achv1", achv1.value)
localStorage.setItem("achv2", achv2.value)
localStorage.setItem("achv3", achv3.value)
localStorage.setItem("stYear1", stYear1.value)
localStorage.setItem("endYear1", endYear1.value)
localStorage.setItem("company1", company1.value)
localStorage.setItem("comLocation1", comLocation1.value)
localStorage.setItem("jobTitle1", jobTitle1.value)
localStorage.setItem("achv11", achv11.value)
localStorage.setItem("achv22", achv22.value)
localStorage.setItem("achv33", achv33.value)
localStorage.setItem("stYear2", stYear2.value)
localStorage.setItem("endYear2", endYear2.value)
localStorage.setItem("company2", company2.value)
localStorage.setItem("comLocation2", comLocation2.value)
localStorage.setItem("jobTitle2", jobTitle2.value)
localStorage.setItem("achv111", achv111.value)
localStorage.setItem("achv222", achv222.value)
localStorage.setItem("achv333", achv333.value)

if(pic.files && pic.files[0]){
 let reader= new FileReader()
 reader.addEventListener("load", ()=>{
    let textImg:any = reader.result
localStorage.setItem("profile_pic", textImg)

 })
 reader.readAsDataURL(pic.files[0])
}

window.location.href = "./resume/resume.html" 

})



